gpu: 0

data:
  name: 'pv'
  root: './data/pv'
  ch: 64
  train_batch_size: 64
  test_batch_size: 1024
  gif_value_lim: 'none'

encoder:
  input_dim: 5
  latent_dim: 20

train:
  loss_fn: 'mse'
  epochs: 1000
  eval_freq: 1
  gif_freq: 1000
  save_freq: 1000
  archive_freq: 1000
  optimizer:
    name: 'adam'
    lr: 1.0e-2
    weight_decay: 0.
    scheduler: 'steplr'
    step_size: 100
    gamma: 0.8
    lowest_lr: 0.
    step_unit: 'epoch'

ctfno1d:
  process: 'linear'
  modes: [10]
  num_blocks: 2
  width: 8
  pad_ratio: [8]
  act: 'gelu'
  C: 1.2
  mid_ch: 16
  freq_ch: 8
  emb_heads: 1